### PR TITLE
Prepare 0.6.1 release

### PR DESCRIPTION
**Pull request by jeromefroe**

### CODE REVIEW

**Comment by webmaster128** [comment]
So we really want to make this a breaking change? Can't this be 0.6.1?

**Comment by jeromefroe** [comment]
> Do we really want to make this a breaking change? Can't this be 0.6.1?

That's what I was going to do originally. But then I remembered the last time the hashbrown dependency was bumped, [I cut a new minor release](https://github.com/jeromefroe/lru-rs/commit/389cf264900a47eb57103883bc75a40bdcec19bf). So just for consistency I was going to do the same. I don't have any strong feelings on this though. It's probably unnecessarily cautious to cut a new version, but I'm just unsure of if this could break someone's setup.

**Comment by webmaster128** [comment]
I don't see an issue with using a patch release but I'm not 100 % sure. Since semver allows even breaking changes in patch releases in 0.x.y, I would not worry too much. Using 0.6.1 would make it easier for users to grap the latest change. But yeah, both ways are fine probably.

**Comment by jeromefroe** [comment]
Yea, on second thought, I'm for using a patch release here since it seems really unlikely any issues would occur, and if they did, I could just yank the release and cut a new one.

**Pull request merged**
