### PR TITLE
Create a version of get_or_insert that doesn't move the key

### PR DESCRIPTION
**Pull request by lufte**
`get_or_insert` is handy but expensive when K is a non-copy type, as it needs to take ownership of the key even when it's already in the cache. This version takes a reference to `K` and only if it doesn't exist, will it clone it (via `ToOwned`) and put it in the cache.

If this addition is acceptable, I will create the missing counterparts to `get_or_insert_mut`, `try_get_or_insert`, and `try_get_or_insert_mut`; as well as the documentation for every method.

I'm really not used to writing much "library code" (with lots of Trait requirements) in Rust, nor unsafe code, so I would really appreciate a careful review from you; although it's pretty much a copy of `get_or_insert` with just a couple of changes.

### CODE REVIEW

**Comment by lufte** [comment]
I also accept suggestions on better names for these methods.

**Comment by jeromefroe** [comment]
Changes look good! Mind just adding a test for the method as well?

**Comment by lufte** [comment]
Done. I added the missing methods, and documentation and tests for all of them.

**Comment by jeromefroe** [comment]
@lufte apologies for the delay getting back to this, mind addressing the issues from CI?

**Comment by lufte** [comment]
No worries. All done, it was just a matter of running cargo fmt.

**Comment by jeromefroe** [comment]
@lufte mind merging master into your branch? I just fixed the issue CI flagged in #200

**Comment by lufte** [comment]
Oops, missed that one. I squashed everything to avoid having some many little commits related to linting and test fixing.

**Comment by jeromefroe** [comment]
Looks great, thanks for the contribution @lufte!

**Pull request merged**
