### PR TITLE
Use MaybeUninit in LL nodes

### PR DESCRIPTION
**Pull request by Firstyear**
This is a work in progress of MaybeUninit, but I'm a bit stuck at the moment and wanted you to review to determine if this is becoming "too invasive" of a change.

The majority of this works and shows how the possibility of abscence in the linked list nodes is in the K,V rather than having partial nodes in the head/tail position. I decided to do this rather than changing the sigil node method, as that reduces a lot of pointer checking an manipulation logic for slicing and extracting.

However, I'm stuck on the following errors:

```
error[E0509]: cannot move out of type `LruEntry<K, V>`, which implements the `Drop` trait
   --> src/lib.rs:519:31
    |
519 |                 unsafe { Some(old_node.val.assume_init()) }
    |                               ^^^^^^^^^^^^
    |                               |
    |                               cannot move out of here
    |                               move occurs because `old_node.val` has type `core::mem::MaybeUninit<V>`, which does not implement the `Copy` trait

error[E0509]: cannot move out of type `LruEntry<K, V>`, which implements the `Drop` trait
   --> src/lib.rs:547:41
    |
547 |         let LruEntry { key, val, .. } = node;
    |                        ---  ---         ^^^^ cannot move out of here
    |                        |    |
    |                        |    ...and here
    |                        data moved here
    |
    = note: move occurs because these variables have types that don't implement the `Copy` trait
```

Drop needs to be implemented on LruEntry with MaybeUninit so ensure the K,V is dropped when LruCache is dropped without all entries being drained. But with Drop present it's not possible to move the K, V out for the functions pop and pop_lru.

So I was hoping you may have some ideas here!

Right now, a possible suggestion is to remove the Drop trait from LruEntry, and move the responsibility for dropping the K,V into LruCache's drop, which would repeatedly pop the Lru to ensure all the K,V's are dropped correctly. 

Anyway, I'd like to know your thoughts on this so far, and if you think it's worth me finishing up, and if you have any suggestions to improve it.

Thanks very much!

### CODE REVIEW

**Comment by jeromefroe** [comment]
This is very interesting!

> Drop needs to be implemented on LruEntry with MaybeUninit so ensure the K,V is dropped when LruCache is dropped without all entries being drained. But with Drop present it's not possible to move the K, V out for the functions pop and pop_lru.

As I understand it, [one can't pull apart the members of a `struct` that implements `Drop`](https://stackoverflow.com/a/34279224). We know that's okay in these instances (`pop` and `pop_lru`) though because we're removing the entry in question from the cache. So I think one possibility would be to add a method to the `LruEntry` that would return it's key and value, and replace the fields in the struct with `mem::MaybeUninit::uninit()`. Then we can safely drop the struct, but will still maintain the invariant that all entries in the cache have valid keys and values.

> Right now, a possible suggestion is to remove the Drop trait from LruEntry, and move the responsibility for dropping the K,V into LruCache's drop, which would repeatedly pop the Lru to ensure all the K,V's are dropped correctly.

I think this would work as well, and would likely require a method like the one mentioned above that would return ownership of the `key` and `val` fields of the `LruEntry` to ensure they are dropped.

Taking a step back and thinking about the general approach, do you think it would be possible to use an `Option` for the `key` and `val` fields instead of `MaybeUninit`? I can't remember if there was a specific reason we don't do that already (and apologies in general for a being a little rusty on this codebase, I haven't yet managed to sneak Rust into my day job so I don't get to write it nearly as much as I hoped I would when I first worked on this crate).

**Comment by Firstyear** [comment]
> This is very interesting!
> 
> > Drop needs to be implemented on LruEntry with MaybeUninit so ensure the K,V is dropped when LruCache is dropped without all entries being drained. But with Drop present it's not possible to move the K, V out for the functions pop and pop_lru.
> 
> As I understand it, [one can't pull apart the members of a `struct` that implements `Drop`](https://stackoverflow.com/a/34279224). We know that's okay in these instances (`pop` and `pop_lru`) though because we're removing the entry in question from the cache. So I think one possibility would be to add a method to the `LruEntry` that would return it's key and value, and replace the fields in the struct with `mem::MaybeUninit::uninit()`. Then we can safely drop the struct, but will still maintain the invariant that all entries in the cache have valid keys and values.

Yes, we could mem::swap these I think rather than doing the destructure yes. But the problem would be that if we mem::swap uninit versions into the LruEntry, when LruEntry is dropped we need to flag that the values are now uninit. This is because LruEntry would still be subject to drop, and now we have a drop condition where the value is uninit, and one where it is init from the main hashmap.

> 
> > Right now, a possible suggestion is to remove the Drop trait from LruEntry, and move the responsibility for dropping the K,V into LruCache's drop, which would repeatedly pop the Lru to ensure all the K,V's are dropped correctly.
> 
> I think this would work as well, and would likely require a method like the one mentioned above that would return ownership of the `key` and `val` fields of the `LruEntry` to ensure they are dropped.

I think this is the only viable solution, but it does add "overhead" at drop time. But I also think that's acceptable too, because during drop this already has to be walked etc. So if it's okay with you I'll do this solution. 

> 
> Taking a step back and thinking about the general approach, do you think it would be possible to use an `Option` for the `key` and `val` fields instead of `MaybeUninit`? I can't remember if there was a specific reason we don't do that already (and apologies in general for a being a little rusty on this codebase, I haven't yet managed to sneak Rust into my day job so I don't get to write it nearly as much as I hoped I would when I first worked on this crate).

Option has a run time check for if == null effective, where as maybeuninit is a compile time check that is "pls trust me I know what I'm doing yolo". 

So you could use option here, but given that every node *except* the sigils will have values, you don't really benefit much from it I think given there are some possible ways to resolve this as we have discussed :)

**Comment by Firstyear** [comment]
Okay, this passes all tests, I tried under miri but I get an error related to ffi which is not from this crate, but it would be great for you to review and check. I think there are some warnings though from me adding some extra unsafes which I should probably clean up ^^;

**Comment by jeromefroe** [comment]
This looks good to me! Thanks again for taking the time to look into this! I know the name of the PR still says "WIP" but unless you have any additional changes you want to make I can go ahead and merge the PR.

**Comment by Firstyear** [comment]
Yep, I just double checked it again, and so long as you are happy with it, feel free to merge. Thanks for your review!

**Pull request merged**
