### PR TITLE
Upgrade to hashbrown v0.13

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by jeromefroe** [comment]
@benesch looks like we'll need to [bump the MSRV to 1.61.0 in order to upgrade to hashbrown v0.13](https://github.com/jeromefroe/lru-rs/blob/master/.github/workflows/main.yml#L19). Mind update the [README](https://github.com/jeromefroe/lru-rs/blob/cf063f6ec292239c716873d53a70094a97e16221/README.md?plain=1#L15) and [CI](https://github.com/jeromefroe/lru-rs/blob/cf063f6ec292239c716873d53a70094a97e16221/.github/workflows/main.yml#L19) as part of this change? That should be all the additional changes we need.

**Comment by benesch** [comment]
Sure thing, done!

**Comment by jeromefroe** [comment]
Looks great! Thank you @benesch!

**Comment by benesch** [comment]
Thank _you_!

**Comment by mrcnski** [comment]
Hello there! I was a bit confused why `lru` version `0.9` is a breaking change, as it seemed to only affect internals. Is it because of this MSRV bump, mentioned in the OP? Should it have been called out in the changelog, perhaps?

**Comment by jeromefroe** [comment]
Hi @mrcnski! Yea, I cut a new minor tag instead of a patch one because of the MSRV bump. Sorry for the confusion, I should have called that out in the changelog 🤦

**Comment by mrcnski** [comment]
No worries at all @jeromefroe, thanks for clearing that up! Have a good day!

**Pull request merged**
